# -*- coding: utf-8 -*-
# src
def build(bld):
  print('→ building src')
  sources=['buffer.cpp', 'chip.cpp', 'dummy.cpp', 'storings.cpp', 'iface.cpp', 'files.cpp', 'parport.cpp', 'timer.cpp', 'protocols.cpp']
  bld(
    features     = 'c', 
    source       = sources,
    includes     = '# ../intl',
    target       = 'maincode'
  )
  bld(
    features     = 'cxx', 
    source       = "main.cpp",
    includes     = '# ../intl',
    target       = 'main.o'
  )
