# gui
def configure(conf):
  print('→ configuring gui')
#  conf.check_cfg(package='gtk+-2.0'  , args='--cflags')
#  conf.check_cfg(package='cairo'     , args='--cflags')
#  conf.check_cfg(package='libxml-2.0', args='--cflags')

def build(bld):
  print('→ building gui')
  bld(
  features = 'c cstlib',
  source  = ["bineditor.c","checksum.c","gui.c","gui_xml.c"],
  target  = 'gui-gtk',
  uselib  = ['GTK+-2.0','CAIRO','LIBXML-2.0'],
  includes= '../intl')
