#include "./icons/logo.xpm"
#include "./icons/empty.xpm"
#include "./icons/erase.xpm"
#include "./icons/read.xpm"
#include "./icons/read_eeprom.xpm"
#include "./icons/write.xpm"
#include "./icons/write_eeprom.xpm"
#include "./icons/lockbit.xpm"
#include "./icons/lockbreak.xpm"
#include "./icons/verify.xpm"
#include "./icons/verify_eeprom.xpm"
#include "./icons/signature.xpm"

